CREATE TABLE outfits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_url VARCHAR(255), NOT NULL
  thumbnail_url TEXT,
  occasion VARCHAR(100) DEFAULT NULL,
  vibe VARCHAR(100) DEFAULT NULL,
  season VARCHAR(50) DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  detected_color VARCHAR(50) DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
